xdebug.mode=trigger
; xdebug.start_with_request=yes
; xdebug.client_host=host.docker.internal
xdebug.client_host=192.168.1.133
xdebug.client_port=9003
xdebug.discover_client_host=false
xdebug.idekey=ANTIGRAVITY
xdebug.log=/tmp/xdebug.log
